### PR TITLE
fix(baseconvrate): Remove and use only currencyhistory

### LINKED ISSUE #1541: Remove BASECONVRATE from CURRENCYFORMATS table
Now we have 2 overlapping implementations of currency rates: one simple inside CURRENCYFORMATS and more sophisticated in dedicated CURRENCYHISTORY table.

My proposal:
* use only CURRENCYHISTORY records
* remove BASECONVRATE field from CURRENCYFORMATS
* do not store meaningless "1" default value in database
* implement following logic to maintain compatibility with current assumptions:
```c
double find_currency_rate_for_given_date(currency curr, date d) {
  if (currencyhistory(curr) is empty || d<oldest in currencyhistory(curr))
    return 1 /* no conversion done if rate is unknown */
  else iterate through currencyhistory(curr) records...
}
```

This should help with #1158, #1183, #1537, improve data model design (removes redundancy) and improve UX.

Problems:
1. Migration from old model for currencies with no CURRENCYHISTORY and with BASECONVRATE <> 1 - there is not enough details available to migrate to new structure. Proposals: a) migrate user's value adding "1900-01-01" date to it b) not migrate BASECONVRATE value to CURRENCYHISTORY
2. Migration from old model BASECONVRATE not matching CURRENCYHISTORY values. Proposals: same as above.

### PR DESCRIPTION
**Pull request by gabriele-v**
Fixes #1541, #646, #1183, #1285, #1530

Requires https://github.com/moneymanagerex/database/pull/30

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1644)

### CODE REVIEW

File: src/db/DB_Table_Currencyformats.h [hunk 1]
```diff
@@ -109,285 +109,285 @@ struct DB_Table_CURRENCYFORMATS : public DB_Table
...
+        db->ExecuteUpdate(wxString::Format("INSERT INTO CURRENCYFORMATS VALUES ('1', '%s', '$', '', '.', ' ', '100', 'USD', 'Fiat', '0')", wxTRANSLATE("US Dollar")));
+        db->ExecuteUpdate(wxString::Format("INSERT INTO CURRENCYFORMATS VALUES ('2', '%s', '%s', '', '.', ' ', '100', 'EUR', 'Fiat', '0')", wxTRANSLATE("Euro"), L"€"));
+        db->ExecuteUpdate(wxString::Format("INSERT INTO CURRENCYFORMATS VALUES ('3', '%s', '%s', '', '.', ' ', '100', 'GBP', 'Fiat', '0')", wxTRANSLATE("Pound Sterling"), L"£"));
+        db->ExecuteUpdate(wxString::Format("INSERT INTO CURRENCYFORMATS VALUES ('4', '%s', '', '%s', ',', ' ', '100', 'RUB', 'Fiat', '0')", wxTRANSLATE("Russian Ruble"), L"р"));
+        db->ExecuteUpdate(wxString::Format("INSERT INTO CURRENCYFORMATS VALUES ('5', '%s', '%s', '', ',', ' ', '100', 'UAH', 'Fiat', '0')", wxTRANSLATE("Hryvnia"), L"₴"));
+        db->ExecuteUpdate(wxString::Format("INSERT INTO CURRENCYFORMATS VALUES ('6', '%s', '%s', '', '.', ' ', '100', 'AFN', 'Fiat', '0')", wxTRANSLATE("Afghani"), L"؋"));
```
Comment (slodki) [inline src/db/DB_Table_Currencyformats.h]: here is ok

File: src/maincurrencydialog.cpp [hunk 2]
```diff
@@ -939,11 +929,14 @@ bool mmMainCurrencyDialog::GetOnlineHistory(std::map<wxDateTime, double> &histor
         if (quotes_closed[i].IsFloat())
         {
             double rate = quotes_closed[i].GetFloat();
-            history[time] = rate;
-            if (first_date > time)
+            if (rate != 1) // Skip rates = 1 (Yahoo returns 1 with invalid Symbols)
```
Comment (slodki) [inline src/maincurrencydialog.cpp]: What with following downloaded history values:
1.11
1.09
1.03
1.00
0.98
0.99
1.00
1.01
?
Two of them ("1.00") will be missing?

File: src/mmhomepagepanel.cpp [hunk 3]
```diff
@@ -131,24 +131,26 @@ void htmlWidgetStocks::calculate_stats(std::map<int, std::pair<double, double> >
...
-        double conv_rate = 1;
+        double today_conv_rate = 1;
+        double purchase_conv_rate = 1;
         Model_Account::Data *account = Model_Account::instance().get(stock.HELDAT);
         if (account)
-        {   
-            Model_Currency::Data *currency = Model_Currency::instance().get(account->CURRENCYID);
-            conv_rate = currency->BASECONVRATE;
+        {
+            today_conv_rate = Model_CurrencyHistory::getDayRate(account->CURRENCYID, today);
```
Comment (slodki) [inline src/mmhomepagepanel.cpp]: We could call just `getDayRate(account->CURRENCYID)` here...

File: src/model/Model_CurrencyHistory.cpp [hunk 4]
```diff
@@ -85,41 +85,68 @@ int Model_CurrencyHistory::addUpdate(const int& currencyID, const wxDate& date,
 /** Return the rate for a specific currency in a specific day*/
 double Model_CurrencyHistory::getDayRate(const int& currencyID, const wxString& DateISO)
```
Comment (slodki) [inline src/model/Model_CurrencyHistory.cpp]: we should add here overloaded version to simplify code:
`double Model_CurrencyHistory::getDayRate(const int& currencyID, const wxDateTime& Date = wxDateTime::Today())`

Then remove all `const wxString today = wxDateTime::Today().FormatISODate();` and simply call `getDayRate(currencyID)`

File: src/model/Model_CurrencyHistory.cpp [hunk 5]
```diff
@@ -85,41 +85,68 @@ int Model_CurrencyHistory::addUpdate(const int& currencyID, const wxDate& date,
...
+        {
+            dFuture.ParseDate(rsFuture.GetAsString(0));
+        }
+
+        if (dPast.IsValid() && dFuture.IsValid())
+        {
+            const wxTimeSpan spanPast = Date.Subtract(dPast);
+            const wxTimeSpan spanFuture = dFuture.Subtract(Date);
+
+            dNearest = spanPast <= spanFuture ? dPast : dFuture;
```
Comment (slodki) [inline src/model/Model_CurrencyHistory.cpp]: This should be ok for currencies - they should be continuous and we can do linear interpolation here.
But for shares (not updated every day) it should be better to use dPast always.

File: src/model/Model_CurrencyHistory.cpp [hunk 6]
```diff
@@ -85,41 +85,68 @@ int Model_CurrencyHistory::addUpdate(const int& currencyID, const wxDate& date,
...
+        {
+            dNearest = dPast;
+        }
+        else if (dFuture.IsValid())
+        {
+            dNearest = dFuture;
+        }
+        else
+        {
+            //TODO: Show warning alert but only one time?
```
Comment (slodki) [inline src/model/Model_CurrencyHistory.cpp]: one time, but per MMEX session. User should be warned every time he runs MMEX that displayed values are wrong because rates are missing.
With buttons: `Download now`, `manually add missing` and `continue [with errors]`

File: src/model/Model_CurrencyHistory.cpp [hunk 7]
```diff
@@ -85,41 +85,68 @@ int Model_CurrencyHistory::addUpdate(const int& currencyID, const wxDate& date,
 /** Return the rate for a specific currency in a specific day*/
 double Model_CurrencyHistory::getDayRate(const int& currencyID, const wxString& DateISO)
 {
-    if (currencyID == Model_Currency::GetBaseCurrency()->CURRENCYID)
+    if (currencyID == Model_Currency::GetBaseCurrency()->CURRENCYID || currencyID == -1)
         return 1;
     
     wxDateTime Date;
     Date.ParseDate(DateISO);
```
Comment (slodki) [inline src/model/Model_CurrencyHistory.cpp]: What we do if DateISO>today?
Can user enter predicted/expected rates into Currency History?
Is it better to use today+1 value then real today-2 one?

File: src/model/Model_CurrencyHistory.cpp [hunk 8]
```diff
@@ -85,41 +85,68 @@ int Model_CurrencyHistory::addUpdate(const int& currencyID, const wxDate& date,
...
-        //}
-        Model_Currency::Data* Currency = Model_Currency::instance().get(currencyID);
-        return Currency->BASECONVRATE;
+        return 1;
     }
 }
 
-/** Return the last attachment number linked to a specific object */
+/** Return the last currency rate */
 double Model_CurrencyHistory::getLastRate(const int& currencyID)
```
Comment (slodki) [inline src/model/Model_CurrencyHistory.cpp]: Should we use `date<today` filtering here?
Should we return *last in table* or *last known* value here?

File: src/model/Model_CurrencyHistory.cpp [hunk 9]
```diff
@@ -130,7 +157,7 @@ double Model_CurrencyHistory::getLastRate(const int& currencyID)
     else
     {
         Model_Currency::Data* Currency = Model_Currency::instance().get(currencyID);
```
Comment (slodki) [inline src/model/Model_CurrencyHistory.cpp]: unused variable?

File: src/reports/cashflow.cpp [hunk 10]
```diff
@@ -69,17 +70,20 @@ void mmReportCashFlow::getStats(double& tInitialBalance, std::vector<ValueTrio>&
             if (wxNOT_FOUND == accountArray_->Index(account.ACCOUNTNAME)) continue;
         }
 
-        const Model_Currency::Data* currency = Model_Account::currency(account);
-        tInitialBalance += account.INITIALBAL * currency->BASECONVRATE;
+        // Use account first transaction date for initial balance
```
Comment (slodki) [inline src/reports/cashflow.cpp]: this is wrong. I have old account with initial amount not used for years - we should add account start date (date for initial amount) to use correct rate to calculate initial amount value.

File: src/db/DB_Table_Currencyformats.h (hunk 1 above)
Comment (gabriele-v) [reply src/db/DB_Table_Currencyformats.h]: Maybe is something related to repository autoencoding?

**Comment by slodki** [comment]
Please add `double Model_CurrencyHistory::getDayRate(const int& currencyID, const wxDateTime& Date = wxDateTime::Today())`
then call it from `double Model_CurrencyHistory::getDayRate(const int& currencyID, const wxString& DateISO)`
This should be trivial and will allow simplify calling it in above PR.

File: src/model/Model_CurrencyHistory.cpp (hunk 4 above)
Comment (gabriele-v) [reply src/model/Model_CurrencyHistory.cpp]: Agree

File: src/maincurrencydialog.cpp (hunk 2 above)
Comment (gabriele-v) [reply src/maincurrencydialog.cpp]: I think it's nearly impossibile that two currencies has exact 1:1 conversion rate

**Comment by vomikan** [comment]
Just reminder. wxDateTime::Today() is very slow function.

**Comment by gabriele-v** [comment]
In that case better to leave as is, I've already put every wxDateTime::Today() as const outside for loops looking for currency rates

File: src/maincurrencydialog.cpp [hunk 11]
```diff
@@ -663,8 +660,7 @@ void mmMainCurrencyDialog::OnHistoryUpdate(wxCommandEvent& /*event*/)
         {
             for (auto &entry : historical_rates)
             {
-                Model_CurrencyHistory::instance().addUpdate(m_currency_id
-                    , entry.first, entry.second, Model_CurrencyHistory::ONLINE);
+                Model_CurrencyHistory::instance().addUpdate(m_currency_id, entry.first, entry.second, Model_CurrencyHistory::ONLINE);
```
Comment (vomikan) [inline src/maincurrencydialog.cpp]: Too long lines is bad. It decrease a code redability.

Comment (gabriele-v) [reply src/maincurrencydialog.cpp]: Up to me it's the opposite: I don't like code that could stay in one line and instead it's divided into two/three. Generally I try to keep it inline if it stays in one line on my FullHD monitor.

File: src/model/Model_CurrencyHistory.cpp (hunk 8 above)
Comment (gabriele-v) [reply src/model/Model_CurrencyHistory.cpp]: Actually it's used only in maincurrencydialog to see rates in the left panel, so it's not important, but I think should be last known

Comment (gabriele-v) [reply src/model/Model_CurrencyHistory.cpp]: Problem is that it will slow down due to  wxDateTime::Today() slowness

File: src/model/Model_CurrencyHistory.cpp (hunk 5 above)
Comment (gabriele-v) [reply src/model/Model_CurrencyHistory.cpp]: What do you mean for shares? If you refer to shares value, than there is StockHistory, if you refer to conversion of shares value, then should be fine because it will try to find nearest conversion for the date of share value, isn't it?

File: src/maincurrencydialog.cpp (hunk 11 above)
Comment (gabriele-v) [reply src/maincurrencydialog.cpp]: Screens are increasing in resolution, if you keep on one line code that could stay on one line, then you need less scrolling to see all the cpp code

File: src/maincurrencydialog.cpp (hunk 2 above)
Comment (slodki) [reply src/maincurrencydialog.cpp]: There are technical currency clones (EUR vs WIR EUR etc.) and some currencies can have similar rates for political reasons. I can imagine ratio oscillating around 1:1

File: src/model/Model_CurrencyHistory.cpp (hunk 5 above)
Comment (slodki) [reply src/model/Model_CurrencyHistory.cpp]: Yes, I'm writing about StockHistory here, for the future...

File: src/model/Model_CurrencyHistory.cpp (hunk 6 above)
Comment (slodki) [reply src/model/Model_CurrencyHistory.cpp]: OK, I will open separate issue for this (to warn user displayed values are pointless)

File: src/model/Model_CurrencyHistory.cpp (hunk 7 above)
Comment (slodki) [reply src/model/Model_CurrencyHistory.cpp]: I'm thinking about blocking entering future values

File: src/model/Model_CurrencyHistory.cpp (hunk 8 above)
Comment (slodki) [reply src/model/Model_CurrencyHistory.cpp]: We can add `getLastRate(const int& currencyID, const wxDateTime& date)` variant for this and call `wxDateTime::Today()` inside maincurrencydialog once

File: src/reports/cashflow.cpp (hunk 10 above)
Comment (slodki) [reply src/reports/cashflow.cpp]: This can be separate PR as it require changes in account table, but we should think about it.

**Comment by slodki** [comment]
`double Model_CurrencyHistory::getDayRate(const int& currencyID, const wxDateTime& Date = wxDateTime::Today())` will not make any additional Today() call if we pass existing value (if we call getDayRate() from loop) or with default (when called not from loop).
This will remove double conversion wxString<->wxDateTime using now. And we still can use wxString variant for values read from sqlite.
This will simplify and speed up our code only.

**Comment by vomikan** [comment]
There is other issue FYI.
Now().OnlyDate() may has hours = timezone. Then if you try compare wxDateTime values they may be not eqvivslent when should be.

Also date is like int type. It's no reasons to use pointer like const wxDateTime& Date

**Comment by slodki** [comment]
@vomikan There is no issue regarding hours. The first step inside getDatRate is to use wxDateTime. My patch change nothing but removes unnecessary wxDateTime->wxString->wxDateTime conversions.

wxDateTime is object instance, duplicating object instance to use it as const is unnecessary.

**Comment by slodki** [comment]
Yahoo response will be skipped only if all values are equal 1
